Prevent signing empty diffs

diff --git a/bin/git-signatures b/bin/git-signatures
--- a/bin/git-signatures
+++ b/bin/git-signatures
@@ -225,6 +225,9 @@ epoch_to_human() {
 
 sig_subject() {
 	local base="${1:-master}"
+	# check for HEAD equal to base
+	[[ "$(git rev-parse "$base")" == "$(git rev-parse HEAD)" ]] && echo "error: cannot sign empty diff" && exit 1
+
 	git diff-tree -p $(git merge-base "$base" HEAD)..HEAD \
 	| git patch-id --stable \
 	| cut -d\  -f1
@@ -297,8 +300,8 @@ cmd_add() {
 		-p|--push) push=1; shift ;;
 		--) shift; break ;;
 	esac done
-	[ "$#" -gt 3 ] && usage add && exit 1
-	[[ "$(git rev-parse --abbrev-ref HEAD)" == "master" ]] && echo "error: cannot create signatures directly on master" && exit 1
+	[ "$#" -gt 2 ] && usage add && exit 1
+
 	ref=${1:-HEAD}
 	base=${2:-master}
 	key=${key_id:-$(git config user.signingKey)}
@@ -306,7 +309,7 @@ cmd_add() {
 		error "invalid_private_key" "$key"; exit 1;
 	}
 
-	sig_subject "$base" \
+	sig_subject "$base" || echo "error: cannot sign empty diff" && exit 1 \
 	| gpg --detach-sign --local-user "$key" \
 	| openssl base64 -A \
 	| git notes --ref signatures append --file=-
